version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - POSTGRES_DB=allomovie
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DATABASE_URL=postgres://user:password@db:5432/allomovie

  #frontend:
  #  build: ./frontend
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ./frontend:/app
  #  depends_on:
  #   - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: allomovie
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
