# Generated by Django 5.0.6 on 2024-06-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, help_text='Select actors for this movie', to='movies.actor'),
        ),
    ]
